# Generated by Django 4.1.7 on 2023-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_usertime_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='middle_initial',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertime',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
