# Generated by Django 4.1.7 on 2023-05-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_usertime_middle_initial_alter_usertime_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/product_images'),
        ),
    ]
