# Generated by Django 4.1.7 on 2023-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_generatedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertime',
            name='month',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.DeleteModel(
            name='generatedTime',
        ),
    ]
