# Generated by Django 4.1.7 on 2023-05-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_usertime_month_delete_generatedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('official_morning_time_in', models.CharField(max_length=255)),
                ('official_morning_time_out', models.CharField(max_length=255)),
                ('official_afternoon_time_in', models.CharField(max_length=255)),
                ('official_afternoon_time_out', models.CharField(max_length=255)),
            ],
        ),
    ]
