# Generated by Django 4.1.7 on 2023-05-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='official_afternoon_time_in',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='official_afternoon_time_out',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='official_morning_time_in',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='official_morning_time_out',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
