# Generated by Django 4.1.7 on 2023-05-15 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_timeentry_official_afternoon_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 11, 40, 46, 363912)),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
