# Generated by Django 4.1.7 on 2023-05-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_timeentry_month_timeentry_year_alter_timeentry_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='year',
            field=models.DateTimeField(default=2023),
        ),
    ]
