# Generated by Django 4.1.7 on 2023-05-15 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_timeentry_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='year',
            field=models.DateField(default=datetime.date(2023, 5, 15)),
        ),
    ]
