# Generated by Django 4.1.7 on 2023-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_timeentry_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
