# Generated by Django 4.1.7 on 2023-05-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_timeentry_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertime',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
