# Generated by Django 4.1.7 on 2023-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_usertime_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='days',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='month',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='official_afternoon_time_in',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='official_afternoon_time_out',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='official_morning_time_in',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='official_morning_time_out',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='year',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='list_of_days',
            field=models.TextField(blank=True),
        ),
    ]
