# Generated by Django 4.1.7 on 2023-05-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_timeentry_time_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='time_user',
        ),
    ]
