# Generated by Django 4.1.7 on 2023-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_timeentry_month_timeentry_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, default=1)),
                ('month', models.IntegerField(blank=True, default=1)),
                ('year', models.IntegerField(default=2023)),
            ],
        ),
    ]
