# Generated by Django 4.1.7 on 2023-05-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='afternoon_suspension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='morning_suspension',
            field=models.BooleanField(default=False),
        ),
    ]
