# Generated by Django 4.1.7 on 2023-05-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_holiday_afternoon_suspension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='remark',
            field=models.CharField(blank=True, default='Holiday', max_length=100),
        ),
    ]
