# Generated by Django 4.1.7 on 2023-05-17 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0040_holiday_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUpClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, default=1)),
                ('month', models.IntegerField(blank=True, default=1)),
                ('year', models.IntegerField(default=2023)),
                ('morning_only', models.BooleanField(default=False)),
                ('afternoon_only', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
