# Generated by Django 4.1.7 on 2023-05-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_makeupclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupclass',
            name='afternoon_time_in',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='makeupclass',
            name='afternoon_time_out',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='makeupclass',
            name='morning_time_in',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='makeupclass',
            name='morning_time_out',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
