# Generated by Django 4.1.7 on 2023-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_makeupclass_afternoon_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
    ]
