import calendar
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
# Create your models here.
class userTime(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user_images/', blank=True, null=True)
    year = models.IntegerField(default=date.today().year)
    month = models.IntegerField(blank=True, default=1)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    middle_initial = models.CharField(max_length=100, blank=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    monday_morning_time_in = models.CharField(max_length=100, blank=True, null=True)
    monday_morning_time_out = models.CharField(max_length=100, blank=True, null=True)
    monday_afternoon_time_in = models.CharField(max_length=100, blank=True, null=True)
    monday_afternoon_time_out = models.CharField(max_length=100, blank=True, null=True)
    tuesday_morning_time_in = models.CharField(max_length=100, blank=True, null=True)
    tuesday_morning_time_out = models.CharField(max_length=100, blank=True, null=True)
    tuesday_afternoon_time_in = models.CharField(max_length=100, blank=True, null=True)
    tuesday_afternoon_time_out = models.CharField(max_length=100, blank=True, null=True)
    wednesday_morning_time_in = models.CharField(max_length=100, blank=True, null=True)
    wednesday_morning_time_out = models.CharField(max_length=100, blank=True, null=True)
    wednesday_afternoon_time_in = models.CharField(max_length=100, blank=True, null=True)
    wednesday_afternoon_time_out = models.CharField(max_length=100, blank=True, null=True)
    thursday_morning_time_in = models.CharField(max_length=100, blank=True, null=True)
    thursday_morning_time_out = models.CharField(max_length=100, blank=True, null=True)
    thursday_afternoon_time_in = models.CharField(max_length=100, blank=True, null=True)
    thursday_afternoon_time_out = models.CharField(max_length=100, blank=True, null=True)
    friday_morning_time_in = models.CharField(max_length=100, blank=True, null=True)
    friday_morning_time_out = models.CharField(max_length=100, blank=True, null=True)
    friday_afternoon_time_in = models.CharField(max_length=100, blank=True, null=True)
    friday_afternoon_time_out = models.CharField(max_length=100, blank=True, null=True)
    saturday_morning_time_in = models.CharField(max_length=100, blank=True, null=True)
    saturday_morning_time_out = models.CharField(max_length=100, blank=True, null=True)
    saturday_afternoon_time_in = models.CharField(max_length=100, blank=True, null=True)
    saturday_afternoon_time_out = models.CharField(max_length=100, blank=True, null=True)
    sunday_morning_time_in = models.CharField(max_length=100, blank=True, null=True)
    sunday_morning_time_out = models.CharField(max_length=100, blank=True, null=True)
    sunday_afternoon_time_in = models.CharField(max_length=100, blank=True, null=True)
    sunday_afternoon_time_out = models.CharField(max_length=100, blank=True, null=True)
    monday_time_in_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    monday_time_out_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    monday_time_in_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    monday_time_out_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_in_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_out_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_in_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_out_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_in_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_out_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_in_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_out_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_in_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_out_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_in_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_out_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_in_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_out_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_in_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_out_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_in_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_out_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_in_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_out_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_in_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_out_morning_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_in_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_out_afternoon_overload_undergrad = models.CharField(max_length=100, blank=True, null=True)
    monday_time_in_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    monday_time_out_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    monday_time_in_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    monday_time_out_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_in_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_out_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_in_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    tuesday_time_out_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_in_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_out_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_in_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    wednesday_time_out_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_in_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_out_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_in_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    thursday_time_out_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_in_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_out_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_in_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    friday_time_out_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_in_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_out_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_in_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    saturday_time_out_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_in_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_out_morning_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_in_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)
    sunday_time_out_afternoon_overload_grad = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
class TimeEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    year = models.IntegerField(default=date.today().year)
    month = models.IntegerField(choices=[(i, calendar.month_name[i]) for i in range(1, 13)], blank=True, default=1)
    list_of_days = models.TextField(blank=True)
    def __str__(self):
        return f"{self.user.username}'s saved times"

class Holiday(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    remarks = models.CharField(blank=True, default="Holiday", max_length=100)
    day = models.IntegerField(blank=True, default=1)
    month = models.IntegerField(blank=True, default=1)
    year = models.IntegerField(default=date.today().year)
    morning_suspension = models.BooleanField(default=False)
    afternoon_suspension = models.BooleanField(default=False)
    
class MakeUpClass(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    morning_time_in = models.CharField(max_length=100, blank=True, default="")
    morning_time_out = models.CharField(max_length=100, blank=True, default="")
    afternoon_time_in  = models.CharField(max_length=100, blank=True, default="")
    afternoon_time_out = models.CharField(max_length=100, blank=True, default="")
    day = models.IntegerField(blank=True, default=1)
    month = models.IntegerField(blank=True, default=1)
    year = models.IntegerField(default=date.today().year)

    def save(self, *args, **kwargs):
        if self.morning_time_in and self.morning_time_in.strip():
            self.morning_time_in = datetime.strptime(self.morning_time_in, '%H:%M').time().strftime('%I:%M %p')
        if self.morning_time_out and self.morning_time_out.strip():
            self.morning_time_out = datetime.strptime(self.morning_time_out, '%H:%M').time().strftime('%I:%M %p')
        if self.afternoon_time_in and self.afternoon_time_in.strip():
            self.afternoon_time_in = datetime.strptime(self.afternoon_time_in, '%H:%M').time().strftime('%I:%M %p')
        if self.afternoon_time_out and self.afternoon_time_out.strip():
            self.afternoon_time_out = datetime.strptime(self.afternoon_time_out, '%H:%M').time().strftime('%I:%M %p')
        super().save(*args, **kwargs)
